# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/
mycar_vin: VIN12345678901234
mycar_baseurl: http://homeassistant.local:5000
